### ISSUE TITLE
Mpi tar file is missing

### ISSUE THREAD

**Issue by mmelendezb** [agumartina/WRFv-4.1.2-Configure-on-CentOS8#1]
**First, whe need MPI libraries to compile all**

```
$ sudo yum install openmpi-devel
$ tar xfz mpich.tar.gz
```
Seems that a line containing the link for downloading mpich.tar.gz is missing?

THanks in advance for the clarification!

**Comment by agumartina** [comment]
Thank you for noticing that @Mishelm2 !
I updated the README   ##:)
